application:
  port: 8000
  hmac_secret: "this-is-a-long-and-secret-example-key-which-has-to-be-greater-or-equal-to-64-bytes"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "http://127.0.0.1"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000